name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for reporting this! I'll try to check your issue and resolve it as quick as possible. If i don't respond in 3 days, contact me at my email adress (on my bio)"
        pr-message: "Thank you so much for your contribution! I'll check your pull request as fast as possible."
